package Telas;

import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import entidades.Cliente;
import entidades.Procedimento;
import servicos.ServicoProcedimento;

public class ConsultaProcedimento extends javax.swing.JFrame {

	/**
	 * Creates new form ConsultaProcedimento
	 */

	ServicoProcedimento servico = new ServicoProcedimento();

	public ConsultaProcedimento() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		botaoVoltar = new javax.swing.JButton();
		labelNome = new javax.swing.JLabel();
		buscaProcedimento = new javax.swing.JTextField();
		consultarProcedimento = new javax.swing.JButton();
		consultarProcedimento.addActionListener(new ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				procurarAtendimentos();
				
			}
		});
		jScrollPane1 = new javax.swing.JScrollPane();
		tabelaProcedimento = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Ramira Estética Facial e Corporal");

		jPanel1.setBackground(new java.awt.Color(255, 153, 153));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Consultar Procedimento");

		botaoVoltar.setBackground(new java.awt.Color(255, 153, 153));
		botaoVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
		botaoVoltar.setText("Voltar");
		botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoVoltarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel1)
						.addGap(108, 108, 108).addComponent(botaoVoltar)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel1)
						.addContainerGap(25, Short.MAX_VALUE))
				.addGroup(
						jPanel1Layout.createSequentialGroup().addComponent(botaoVoltar).addGap(0, 0, Short.MAX_VALUE)));

		labelNome.setText("Nome");

		consultarProcedimento.setBackground(new java.awt.Color(255, 153, 153));
		consultarProcedimento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		consultarProcedimento.setForeground(new java.awt.Color(255, 255, 255));
		consultarProcedimento.setText("Pesquisar");

		tabelaProcedimento.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Nome", "Valor" }) {
			Class[] types = new Class[] { java.lang.String.class, java.lang.Float.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jScrollPane1.setViewportView(tabelaProcedimento);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup().addGap(49, 49, 49)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(labelNome)
								.addGroup(layout.createSequentialGroup()
										.addComponent(buscaProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, 265,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(consultarProcedimento)))
						.addContainerGap(32, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(37, 37, 37).addComponent(labelNome)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(buscaProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(consultarProcedimento))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 75, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {
		new TelaProcedimentos().setVisible(true);
		this.dispose();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ConsultaProcedimento.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ConsultaProcedimento.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ConsultaProcedimento.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ConsultaProcedimento.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ConsultaProcedimento().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton botaoVoltar;
	private javax.swing.JTextField buscaProcedimento;
	private javax.swing.JButton consultarProcedimento;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel labelNome;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tabelaProcedimento;
	// End of variables declaration
	
	
	private void procurarAtendimentos() {
		String nome = buscaProcedimento.getText();
		List<Procedimento> procedimentos = null;
		procedimentos = servico.buscaPorNome(nome);

		DefaultTableModel modeloTabela = (DefaultTableModel) tabelaProcedimento.getModel();

		for (int i = 0; i < procedimentos.size(); i++) {
			modeloTabela.addRow(new String[modeloTabela.getColumnCount()]);
			tabelaProcedimento.setValueAt(procedimentos.get(i).getNome(), i, 0);
			tabelaProcedimento.setValueAt(procedimentos.get(i).getValor(), i, 1);
			
		}
	}
}
